export const FETCH_PRODUCTS_SUCCESS="FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAIL="FETCH_PRODUCTS_FAIL";

export const POST_PRODUCTS_SUCCESS="POST_PRODUCTS_SUCCESS";
export const POST_PRODUCTS_FAIL="POST_PRODUCTS_FAIL";

export const LIKE_DISLIKE_SUCCESS="LIKE_DISLIKE_SUCCESS";
export const LIKE_DISLIKE_FAILED="LIKE_DISLIKE_FAILED";
