export const ADD_TOCART="ADD_TOCART";
export const GET_FROM_CART="GET_FROM_CART";
export const INCREMENT="INCREMENT";
export const DECREMENT="DECREMENT";
export const UPDATE_ON_DELETE="UPDATE_ON_DELETE";
export const RESET_STORE="RESET_STORE";
export const RESET_STORE_ATTENTE="RESET_STORE_ATTENTE";
export const ATTENTE_DELETE="ATTENTE_DELETE";
export const SWITCH_DATA="SWITCH_DATA";
export const UPDATE_ON_DELETE_ATTENTE="UPDATE_ON_DELETE_ATTENTE";
export const INCREMENT_ATTENTE="INCREMENT_ATTENTE";
export const DECREMENT_ATTENTE="DECREMENT_ATTENTE";

